"""Generate nanobind C++ bindings from a parsed header IR."""

from __future__ import annotations
import sys
from collections import Counter, defaultdict
from io import StringIO
from pathlib import Path

from magicbind.header_parser import (
    IRTU, IREnum, IRStruct, IRClass, IRFunction,
    walk_tu,
)

import clang.cindex as cl


def _qualified(namespace: str, name: str) -> str:
    return f"{namespace}::{name}" if namespace else name

def _rv_policy(return_type: str) -> str | None:
    rt = return_type.strip()
    if rt.endswith("*") or (rt.endswith("&") and not rt.startswith("const")):
        return "nb::rv_policy::reference"
    return None

def _param_types(fn: IRFunction) -> str:
    return ", ".join(p.type for p in fn.params)

def _overloaded(methods: list[IRFunction]) -> set[str]:
    return {name for name, n in Counter(m.name for m in methods).items() if n > 1}


class Emitter:
    def __init__(self, module_name: str) -> None:
        self.module_name = module_name
        self._buf = StringIO()
        self._indent = 0

    def _w(self, line: str = "") -> None:
        if line:
            self._buf.write("    " * self._indent + line + "\n")
        else:
            self._buf.write("\n")

    def blank(self) -> None:
        self._buf.write("\n")

    def getvalue(self) -> str:
        return self._buf.getvalue()

    def emit_file_header(self, tu: IRTU) -> None:
        header = Path(tu.source_file).name
        self._w(f"// Auto-generated nanobind bindings for {header}")
        self._w( "// Generated by codegen.py — do not edit by hand.")
        self._w()
        self._w( '#include <nanobind/nanobind.h>')
        self._w( '#include <nanobind/ndarray.h>')
        self._w( '#include <nanobind/stl/string.h>')
        self._w( '#include <nanobind/stl/vector.h>')
        self._w( '#include <nanobind/stl/pair.h>')
        self._w( '#include <nanobind/stl/optional.h>')
        self._w( '#include <nanobind/stl/map.h>')
        self._w( '#include <nanobind/stl/tuple.h>')
        self._w( '#include <nanobind/stl/array.h>')
        self._w( '#include <nanobind/stl/unordered_map.h>')
        self._w( '#include <nanobind/stl/set.h>')
        self._w( '#include <nanobind/stl/unordered_set.h>')
        self._w( '#include <nanobind/stl/variant.h>')
        self._w( '#include <nanobind/stl/string_view.h>')
        self._w( '#include <nanobind/stl/complex.h>')
        self._w( '#include <nanobind/stl/shared_ptr.h>')
        self._w( '#include <nanobind/stl/unique_ptr.h>')
        self._w( '#include <nanobind/stl/filesystem.h>')
        self._w( '#include "magicbind_opencv.h"')
        self._w(f'#include "{header}"')
        self._w()
        self._w("namespace nb = nanobind;")
        self._w()

    def emit_module_open(self) -> None:
        self._w(f"NB_MODULE({self.module_name}, m) {{")
        self._indent += 1

    def emit_module_close(self) -> None:
        self._indent -= 1
        self._w("}")

    def emit_enum(self, en: IREnum) -> None:
        fqn = _qualified(en.namespace, en.name)
        if en.comment:
            self._w(f"// {en.comment}")
        self._w(f'nb::enum_<{fqn}>(m, "{en.name}")')
        self._indent += 1
        for i, v in enumerate(en.values):
            suffix = ";" if i == len(en.values) - 1 else ""
            self._w(f'.value("{v.name}", {fqn}::{v.name}){suffix}')
        self._indent -= 1
        self._w()

    def emit_struct(self, st: IRStruct) -> None:
        fqn = st.cpp_type if st.cpp_type else _qualified(st.namespace, st.name)
        if st.comment:
            self._w(f"// {st.comment}")
        self._w(f'nb::class_<{fqn}>(m, "{st.name}")')
        self._indent += 1
        self._w('.def(nb::init<>())')
        for f in st.fields:
            rw = "def_ro" if f.is_const else "def_rw"
            self._w(f'.{rw}("{f.name}", &{fqn}::{f.name})')
        if st.fields:
            self._w(f'.def("__repr__", [](const {fqn} &v) {{')
            self._indent += 1
            self._w(f'return std::string("{st.name}(") +')
            self._indent += 1
            for i, f in enumerate(st.fields):
                sep = ' + ", " + ' if i < len(st.fields) - 1 else ""
                self._w(f'std::string("{f.name}=") + nb::cast<std::string>(nb::str(nb::cast(v.{f.name}))){sep}')
            self._indent -= 1
            self._w('+ ")";')
            self._indent -= 1
            self._w('})')
        self._w(';')
        self._indent -= 1
        self._w()

    def emit_class(self, cls: IRClass) -> None:
        fqn = cls.cpp_type if cls.cpp_type else _qualified(cls.namespace, cls.name)
        if cls.comment:
            self._w(f"// {cls.comment}")
        self._w(f'nb::class_<{fqn}>(m, "{cls.name}")')
        self._indent += 1
        for ctor in cls.constructors:
            self._w(f'.def(nb::init<{_param_types(ctor)}>())')
        for f in cls.fields:
            rw = "def_ro" if f.is_const else "def_rw"
            self._w(f'.{rw}("{f.name}", &{fqn}::{f.name})')
        # skip overload_cast for template instantiations — param types are still spelled as T/U
        overloaded = set() if cls.cpp_type else _overloaded(cls.methods)
        for fn in cls.methods:
            self._emit_method(fn, fqn, overloaded)
        self._w(';')
        self._indent -= 1
        self._w()

    def _emit_method(self, fn: IRFunction, fqn: str, overloaded: set[str]) -> None:
        if fn.name.startswith("~"):
            return
        py_name  = fn.operator_sym or fn.name
        def_type = "def_static" if fn.is_static else "def"
        if fn.name in overloaded:
            const_q = " const" if fn.is_const else ""
            ptr = f"nb::overload_cast<{_param_types(fn)}>(&{fqn}::{fn.name}{const_q})"
        else:
            ptr = f"&{fqn}::{fn.name}"
        rvp     = _rv_policy(fn.return_type)
        extra   = f", {rvp}" if rvp else ""
        comment = f"  // {fn.comment}" if fn.comment else ""
        self._w(f'.{def_type}("{py_name}", {ptr}{extra}){comment}')

    def emit_free_function(self, fn: IRFunction, overloaded: bool = False) -> None:
        fqn     = _qualified(fn.namespace, fn.name)
        rvp     = _rv_policy(fn.return_type)
        extra   = f", {rvp}" if rvp else ""
        comment = f"  // {fn.comment}" if fn.comment else ""
        ptr     = f"nb::overload_cast<{_param_types(fn)}>(&{fqn})" if overloaded else f"&{fqn}"
        self._w(f'm.def("{fn.name}", {ptr}{extra});{comment}')

    def emit_namespace_open(self, ns: str) -> None:
        var = ns.replace("::", "_").lower() + "_m"
        self._w(f'auto {var} = m.def_submodule("{ns.split("::")[-1]}", "{ns} submodule");')
        self._w('{')
        self._indent += 1
        self._w(f'auto& m = {var};  // shadow outer m so emit helpers write into the submodule')
        self._w('(void)m;')

    def emit_namespace_close(self) -> None:
        self._indent -= 1
        self._w('}')
        self._w()


def generate(tu: IRTU, module_name: str) -> str:
    em = Emitter(module_name)
    em.emit_file_header(tu)
    em.emit_module_open()

    by_ns: dict[str, list] = defaultdict(list)
    for node in (*tu.enums, *tu.structs, *tu.classes):
        by_ns[node.namespace].append(node)

    def emit_nodes(nodes: list) -> None:
        for node in nodes:
            if isinstance(node, IREnum):
                em.emit_enum(node)
            elif isinstance(node, IRStruct):
                em.emit_struct(node)
            elif isinstance(node, IRClass):
                em.emit_class(node)

    emit_nodes(by_ns.get("", []))

    overloaded_fns = _overloaded(tu.functions)
    for fn in tu.functions:
        em.emit_free_function(fn, overloaded=fn.name in overloaded_fns)
    if tu.functions:
        em.blank()

    for ns, nodes in by_ns.items():
        if not ns:
            continue
        em.emit_namespace_open(ns)
        emit_nodes(nodes)
        em.emit_namespace_close()

    em.emit_module_close()
    return em.getvalue()


def generate_from_header(
    header: Path,
    module_name: str | None = None,
    clang_args: list[str] | None = None,
) -> str:
    if not header.exists():
        raise FileNotFoundError(f"Not found: {header}")

    parse_args = ["-x", "c++-header", *(clang_args or [])]
    if not any(a.startswith("-std=") for a in parse_args):
        parse_args.append("-std=c++20")

    index = cl.Index.create()
    tu_cursor = index.parse(
        str(header),
        args=parse_args,
        options=(
            cl.TranslationUnit.PARSE_DETAILED_PROCESSING_RECORD |
            cl.TranslationUnit.PARSE_SKIP_FUNCTION_BODIES
        ),
    )

    errors = [
        d for d in tu_cursor.diagnostics
        if d.severity >= cl.Diagnostic.Error
        and d.location.file
        and Path(d.location.file.name).resolve() == header.resolve()
    ]
    if errors:
        for d in errors:
            print(f"[error] {d.spelling}", file=sys.stderr)
        print("[warn] continuing — bindings may be incomplete", file=sys.stderr)

    ir = walk_tu(tu_cursor.cursor, header)
    return generate(ir, module_name or header.stem)
